### PR TITLE
Add coverage for pytest

### PR DESCRIPTION
**Pull request by hslusarek**
Adds coverage report for pytest.

### CODE REVIEW

**Comment by agutenkunst** [comment]
Since this needs python-pytest-cov should it declare a dependency?

**Comment by agutenkunst** [comment]
I added/resorted some lines. Especially considering the parallel test execution.

**Comment by jschleicher** [comment]
@machinekoder Could you please take a look at the PR for coverage reports and review it?

**Comment by machinekoder** [comment]
@hslusarek @agutenkunst @jschleicher Thank you for the contribution.

**Pull request merged**
